# 1. The Service (MetalLB Connector)
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  type: LoadBalancer
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ .Release.Name }}-mysql
---
# 2. The Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize }}  # Pulls from values.yaml
---
# 3. The Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mysql
    spec:
      containers:
      - image: {{ .Values.image }}     # Pulls from values.yaml
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass-secret  # The name of the secret you created
              key: password            # The key inside that secret
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mysql-pvc